#!/bin/bash

SECONDS=0

indir=${1} # directory where input is
outdir=${2} # directory where output is saved
ndirs=${3} # number of jobs

#ndirs=$(ls -l ${indir} | grep -c ^d)
#echo 'Processing '${ndirs}' jobs'

cmd="aliroot -b -q 'RunClusterizer.C(\"${indir}\",\"${outdir}\",'${ndirs}')'"
eval $cmd
